prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector: {}

    retention: 7d

grafana:
  enabled: true

alertmanager:
  enabled: true

  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring