apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-agent
  namespace: release-agent
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: release-agent
spec:
  replicas: 3

  selector:
    matchLabels:
      app: release-agent

  template:
    metadata:
      labels:
        app: release-agent
    spec:
      containers:
        - name: release-agent
          image: ghcr.io/shinjukupikachu/personal_project:345efd2
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:
            - secretRef:
                name: release-pilot-secrets

          volumeMounts:
            - name: release-pilot-data
              mountPath: /app/data

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: release-pilot-data
          persistentVolumeClaim:
            claimName: release-pilot-data
